import { create } from 'zustand'
import type { TripParams, ItineraryData, ChecklistItem, OptimizationType } from '@/types'
import { generateRoute } from '@/engine/routeGenerator'
import { recalculateTime } from '@/engine/timeRecalculator'
import { generateChecklist } from '@/engine/checklistGenerator'

interface TripStore {
  params: TripParams | null
  itinerary: ItineraryData | null
  checklist: ChecklistItem[]
  isGenerating: boolean
  setParams: (params: TripParams) => void
  generate: (params: TripParams) => void
  moveSpot: (spotId: string, fromDay: number, toDay: number, toIndex: number) => void
  applyOptimization: (type: OptimizationType) => void
  toggleChecklistItem: (id: string) => void
  addChecklistItem: (category: string, name: string) => void
  removeChecklistItem: (id: string) => void
  buildChecklist: () => void
  exportChecklist: () => string
}

export const useTripStore = create<TripStore>((set, get) => ({
  params: null,
  itinerary: null,
  checklist: [],
  isGenerating: false,

  setParams: (params) => set({ params }),

  generate: (params) => {
    set({ isGenerating: true, params, checklist: [] })
    setTimeout(() => {
      const itinerary = generateRoute(params)
      const checklist = generateChecklist(itinerary)
      set({ itinerary, checklist, isGenerating: false })
    }, 2000)
  },

  moveSpot: (spotId, fromDay, toDay, toIndex) => {
    const { itinerary } = get()
    if (!itinerary) return

    const newRoutes = itinerary.routes.map((route) => ({
      ...route,
      spots: [...route.spots],
    }))

    const fromRoute = newRoutes.find((r) => r.day === fromDay)
    const toRoute = newRoutes.find((r) => r.day === toDay)
    if (!fromRoute || !toRoute) return

    const spotIndex = fromRoute.spots.findIndex((s) => s.id === spotId)
    if (spotIndex === -1) return

    const [movedSpot] = fromRoute.spots.splice(spotIndex, 1)
    toRoute.spots.splice(toIndex, 0, movedSpot)

    const updated = recalculateTime({ ...itinerary, routes: newRoutes })
    set({ itinerary: updated })
  },

  applyOptimization: (type) => {
    const { itinerary } = get()
    if (!itinerary) return

    const newRoutes = itinerary.routes.map((route) => ({
      ...route,
      spots: [...route.spots],
    }))

    if (type === 'less_drive') {
      newRoutes.forEach((route) => {
        const scenicSpots = route.spots.filter(
          (s) => s.type === 'scenic' || s.type === 'rest'
        )
        if (scenicSpots.length > 2 && route.drivingDuration > 4) {
          const lastScenic = scenicSpots[scenicSpots.length - 1]
          const idx = route.spots.findIndex((s) => s.id === lastScenic.id)
          if (idx !== -1) {
            route.spots.splice(idx, 1)
          }
        }
      })
    }

    if (type === 'early_hotel') {
      newRoutes.forEach((route) => {
        const hotelIdx = route.spots.findIndex((s) => s.type === 'hotel')
        if (hotelIdx !== -1) {
          const hotel = route.spots.splice(hotelIdx, 1)[0]
          const scenicSpots = route.spots.filter((s) => s.type === 'scenic')
          if (scenicSpots.length > 1) {
            const insertAfter = route.spots.findIndex(
              (s) => s.id === scenicSpots[Math.floor(scenicSpots.length / 2)].id
            )
            route.spots.splice(insertAfter + 1, 0, hotel)
          } else {
            route.spots.push(hotel)
          }
        }
      })
    }

    if (type === 'add_lunch') {
      newRoutes.forEach((route) => {
        const hasRestaurant = route.spots.some((s) => s.type === 'restaurant')
        if (!hasRestaurant) {
          const scenicSpots = route.spots.filter((s) => s.type === 'scenic')
          if (scenicSpots.length >= 1) {
            const midIdx = Math.floor(scenicSpots.length / 2)
            const afterSpot = scenicSpots[midIdx]
            const insertIdx = route.spots.findIndex((s) => s.id === afterSpot.id) + 1
            route.spots.splice(insertIdx, 0, {
              id: `lunch-${route.day}-${Date.now()}`,
              name: '沿途特色餐厅',
              type: 'restaurant',
              arrivalTime: '12:00',
              duration: 1,
              mileage: 0,
              description: '当地特色美食，休息用餐',
            })
          }
        }
      })
    }

    const updated = recalculateTime({ ...itinerary, routes: newRoutes })
    set({ itinerary: updated })
  },

  toggleChecklistItem: (id) => {
    set((state) => ({
      checklist: state.checklist.map((item) =>
        item.id === id ? { ...item, checked: !item.checked } : item
      ),
    }))
  },

  addChecklistItem: (category, name) => {
    set((state) => ({
      checklist: [
        ...state.checklist,
        {
          id: `custom-${Date.now()}`,
          category,
          name,
          checked: false,
          autoGenerated: false,
        },
      ],
    }))
  },

  removeChecklistItem: (id) => {
    set((state) => ({
      checklist: state.checklist.filter((item) => item.id !== id),
    }))
  },

  buildChecklist: () => {
    const { itinerary } = get()
    if (!itinerary) return
    const checklist = generateChecklist(itinerary)
    set({ checklist })
  },

  exportChecklist: () => {
    const { checklist, itinerary } = get()
    if (!itinerary) {
      let text = '🚗 路书行 - 出发清单\n\n'
      const grouped: Record<string, typeof checklist> = {}
      checklist.forEach((item) => {
        if (!grouped[item.category]) grouped[item.category] = []
        grouped[item.category].push(item)
      })
      Object.entries(grouped).forEach(([category, items]) => {
        text += `【${category}】\n`
        items.forEach((item) => {
          text += `  ${item.checked ? '✅' : '⬜'} ${item.name}\n`
        })
        text += '\n'
      })
      return text
    }

    const totalMileage = itinerary.routes.reduce((sum, r) => sum + r.totalMileage, 0)
    const totalDriveHours = itinerary.routes.reduce((sum, r) => sum + r.drivingDuration, 0)
    const vehicleLabel =
      itinerary.params.vehicleType === 'fuel' ? '燃油车' :
      itinerary.params.vehicleType === 'electric' ? '电动车' : '混动车'
    const preferenceLabels: Record<string, string> = {
      scenic: '看景',
      family: '亲子',
      camping: '露营',
      less_mountain: '少走山路',
    }
    const preferenceStr = itinerary.params.preferences
      .map((p) => preferenceLabels[p] || p)
      .join('、') || '无'

    let header = `🚗 路书行 - 出发清单
━━━━━━━━━━━━━━━━━━━━━━━━
📍 出发地：${itinerary.params.departure}
📅 出行天数：${itinerary.params.days}天
👥 同行人数：${itinerary.params.companions}人
🚙 车辆类型：${vehicleLabel}
⏱️ 每日驾驶：${itinerary.params.dailyDriveHours}小时
🎯 出行偏好：${preferenceStr}
📊 总里程：约 ${totalMileage} km
⏰ 总驾驶时长：约 ${Math.round(totalDriveHours)} 小时
━━━━━━━━━━━━━━━━━━━━━━━━

📅 每日行程概览：
`
    itinerary.routes.forEach((route) => {
      const scenicSpots = route.spots.filter((s) => s.type === 'scenic').map((s) => s.name).join('、')
      header += `  D${route.day} (${route.date})：${route.totalMileage}km · ${route.drivingDuration}h驾驶
    景点：${scenicSpots || '无'}
`
    })

    header += `
━━━━━━━━━━━━━━━━━━━━━━━━
📋 物品清单：
`

    const grouped: Record<string, typeof checklist> = {}
    checklist.forEach((item) => {
      if (!grouped[item.category]) grouped[item.category] = []
      grouped[item.category].push(item)
    })

    let text = header
    Object.entries(grouped).forEach(([category, items]) => {
      text += `\n【${category}】\n`
      items.forEach((item) => {
        text += `  ${item.checked ? '✅' : '⬜'} ${item.name}\n`
      })
    })

    return text
  },
}))
