import { create } from 'zustand'
import type { TripParams, ItineraryData, ChecklistItem, OptimizationType } from '@/types'
import { generateRoute } from '@/engine/routeGenerator'
import { recalculateTime } from '@/engine/timeRecalculator'
import { generateChecklist } from '@/engine/checklistGenerator'

interface TripStore {
  params: TripParams | null
  itinerary: ItineraryData | null
  checklist: ChecklistItem[]
  isGenerating: boolean
  setParams: (params: TripParams) => void
  generate: (params: TripParams) => void
  moveSpot: (spotId: string, fromDay: number, toDay: number, toIndex: number) => void
  applyOptimization: (type: OptimizationType) => void
  toggleChecklistItem: (id: string) => void
  addChecklistItem: (category: string, name: string) => void
  removeChecklistItem: (id: string) => void
  buildChecklist: () => void
  exportChecklist: () => string
}

export const useTripStore = create<TripStore>((set, get) => ({
  params: null,
  itinerary: null,
  checklist: [],
  isGenerating: false,

  setParams: (params) => set({ params }),

  generate: (params) => {
    set({ isGenerating: true, params })
    setTimeout(() => {
      const itinerary = generateRoute(params)
      set({ itinerary, isGenerating: false })
    }, 2000)
  },

  moveSpot: (spotId, fromDay, toDay, toIndex) => {
    const { itinerary } = get()
    if (!itinerary) return

    const newRoutes = itinerary.routes.map((route) => ({
      ...route,
      spots: [...route.spots],
    }))

    const fromRoute = newRoutes.find((r) => r.day === fromDay)
    const toRoute = newRoutes.find((r) => r.day === toDay)
    if (!fromRoute || !toRoute) return

    const spotIndex = fromRoute.spots.findIndex((s) => s.id === spotId)
    if (spotIndex === -1) return

    const [movedSpot] = fromRoute.spots.splice(spotIndex, 1)
    toRoute.spots.splice(toIndex, 0, movedSpot)

    const updated = recalculateTime({ ...itinerary, routes: newRoutes })
    set({ itinerary: updated })
  },

  applyOptimization: (type) => {
    const { itinerary } = get()
    if (!itinerary) return

    const newRoutes = itinerary.routes.map((route) => ({
      ...route,
      spots: [...route.spots],
    }))

    if (type === 'less_drive') {
      newRoutes.forEach((route) => {
        const scenicSpots = route.spots.filter(
          (s) => s.type === 'scenic' || s.type === 'rest'
        )
        if (scenicSpots.length > 2 && route.drivingDuration > 4) {
          const lastScenic = scenicSpots[scenicSpots.length - 1]
          const idx = route.spots.findIndex((s) => s.id === lastScenic.id)
          if (idx !== -1) {
            route.spots.splice(idx, 1)
          }
        }
      })
    }

    if (type === 'early_hotel') {
      newRoutes.forEach((route) => {
        const hotelIdx = route.spots.findIndex((s) => s.type === 'hotel')
        if (hotelIdx !== -1) {
          const hotel = route.spots.splice(hotelIdx, 1)[0]
          const scenicSpots = route.spots.filter((s) => s.type === 'scenic')
          if (scenicSpots.length > 1) {
            const insertAfter = route.spots.findIndex(
              (s) => s.id === scenicSpots[Math.floor(scenicSpots.length / 2)].id
            )
            route.spots.splice(insertAfter + 1, 0, hotel)
          } else {
            route.spots.push(hotel)
          }
        }
      })
    }

    if (type === 'add_lunch') {
      newRoutes.forEach((route) => {
        const hasRestaurant = route.spots.some((s) => s.type === 'restaurant')
        if (!hasRestaurant) {
          const scenicSpots = route.spots.filter((s) => s.type === 'scenic')
          if (scenicSpots.length >= 1) {
            const midIdx = Math.floor(scenicSpots.length / 2)
            const afterSpot = scenicSpots[midIdx]
            const insertIdx = route.spots.findIndex((s) => s.id === afterSpot.id) + 1
            route.spots.splice(insertIdx, 0, {
              id: `lunch-${route.day}-${Date.now()}`,
              name: '沿途特色餐厅',
              type: 'restaurant',
              arrivalTime: '12:00',
              duration: 1,
              mileage: 0,
              description: '当地特色美食，休息用餐',
            })
          }
        }
      })
    }

    const updated = recalculateTime({ ...itinerary, routes: newRoutes })
    set({ itinerary: updated })
  },

  toggleChecklistItem: (id) => {
    set((state) => ({
      checklist: state.checklist.map((item) =>
        item.id === id ? { ...item, checked: !item.checked } : item
      ),
    }))
  },

  addChecklistItem: (category, name) => {
    set((state) => ({
      checklist: [
        ...state.checklist,
        {
          id: `custom-${Date.now()}`,
          category,
          name,
          checked: false,
          autoGenerated: false,
        },
      ],
    }))
  },

  removeChecklistItem: (id) => {
    set((state) => ({
      checklist: state.checklist.filter((item) => item.id !== id),
    }))
  },

  buildChecklist: () => {
    const { itinerary } = get()
    if (!itinerary) return
    const checklist = generateChecklist(itinerary)
    set({ checklist })
  },

  exportChecklist: () => {
    const { checklist, itinerary } = get()
    const header = itinerary
      ? `🚗 路书行 - 出发清单\n📍 出发地：${itinerary.params.departure}\n📅 天数：${itinerary.params.days}天\n\n`
      : '🚗 路书行 - 出发清单\n\n'

    const grouped: Record<string, ChecklistItem[]> = {}
    checklist.forEach((item) => {
      if (!grouped[item.category]) grouped[item.category] = []
      grouped[item.category].push(item)
    })

    let text = header
    Object.entries(grouped).forEach(([category, items]) => {
      text += `【${category}】\n`
      items.forEach((item) => {
        text += `  ${item.checked ? '✅' : '⬜'} ${item.name}\n`
      })
      text += '\n'
    })

    return text
  },
}))
