import type { ItineraryData, ChecklistItem } from '@/types'

const BASE_CATEGORIES: { category: string; items: string[] }[] = [
  {
    category: '证件资料',
    items: ['身份证', '驾驶证', '行驶证', '车辆保险单', '身份证复印件'],
  },
  {
    category: '车辆检查',
    items: ['轮胎胎压检查', '机油/冷却液', '刹车系统', '灯光检查', '备胎及工具', '车载充电器'],
  },
  {
    category: '导航通讯',
    items: ['手机支架', '车载充电线', '离线地图下载', '对讲机(多车)'],
  },
  {
    category: '应急物品',
    items: ['急救包', '三角警示牌', '灭火器', '拖车绳', '搭电线', '反光背心'],
  },
]

const WEATHER_ITEMS: { category: string; items: string[] }[] = [
  {
    category: '保暖衣物',
    items: ['冲锋衣', '抓绒衣', '保暖内衣', '手套', '围巾'],
  },
  {
    category: '防晒用品',
    items: ['防晒霜SPF50+', '太阳镜', '遮阳帽', '冰袖'],
  },
]

const CAMPING_ITEMS: { category: string; items: string[] }[] = [
  {
    category: '露营装备',
    items: ['帐篷', '睡袋', '防潮垫', '营地灯', '折叠桌椅', '炊具套装', '气罐', '打火机'],
  },
]

const FAMILY_ITEMS: { category: string; items: string[] }[] = [
  {
    category: '亲子用品',
    items: ['儿童安全座椅', '零食饮料', '玩具/绘本', '儿童常用药品', '换洗衣物'],
  },
]

const ELECTRIC_ITEMS: { category: string; items: string[] }[] = [
  {
    category: '充电相关',
    items: ['充电卡/APP', '便携充电枪', '充电延长线', '充电桩地图'],
  },
]

export function generateChecklist(itinerary: ItineraryData): ChecklistItem[] {
  const items: ChecklistItem[] = []
  let idCounter = 0

  const addItem = (category: string, name: string) => {
    items.push({
      id: `cl-${idCounter++}`,
      category,
      name,
      checked: false,
      autoGenerated: true,
    })
  }

  BASE_CATEGORIES.forEach((cat) => {
    cat.items.forEach((name) => addItem(cat.category, name))
  })

  WEATHER_ITEMS.forEach((cat) => {
    cat.items.forEach((name) => addItem(cat.category, name))
  })

  if (itinerary.params.preferences.includes('camping')) {
    CAMPING_ITEMS.forEach((cat) => {
      cat.items.forEach((name) => addItem(cat.category, name))
    })
  }

  if (itinerary.params.preferences.includes('family')) {
    FAMILY_ITEMS.forEach((cat) => {
      cat.items.forEach((name) => addItem(cat.category, name))
    })
  }

  if (itinerary.params.vehicleType === 'electric') {
    ELECTRIC_ITEMS.forEach((cat) => {
      cat.items.forEach((name) => addItem(cat.category, name))
    })
  }

  const totalMileage = itinerary.routes.reduce((sum, r) => sum + r.totalMileage, 0)
  if (totalMileage > 1000) {
    addItem('车辆检查', '建议出行前做一次全面保养')
  }

  const maxDayMileage = Math.max(...itinerary.routes.map((r) => r.totalMileage))
  if (maxDayMileage > 400) {
    addItem('应急物品', '建议携带备用油桶(燃油车)')
  }

  if (itinerary.params.days > 3) {
    addItem('生活用品', '洗衣液/晾衣绳')
    addItem('生活用品', '多功能插座')
  }

  return items
}
