export type VehicleType = 'fuel' | 'electric' | 'hybrid'
export type Preference = 'scenic' | 'family' | 'camping' | 'less_mountain'
export type SpotType = 'scenic' | 'restaurant' | 'hotel' | 'service_area' | 'rest'
export type OptimizationType = 'less_drive' | 'early_hotel' | 'add_lunch'

export interface TripParams {
  departure: string
  days: number
  companions: number
  vehicleType: VehicleType
  dailyDriveHours: number
  preferences: Preference[]
}

export interface Spot {
  id: string
  name: string
  type: SpotType
  arrivalTime: string
  duration: number
  mileage: number
  description: string
}

export interface DayRoute {
  day: number
  date: string
  totalMileage: number
  drivingDuration: number
  serviceAreas: string[]
  fuelChargeSuggestion: string
  spots: Spot[]
}

export interface ItineraryData {
  params: TripParams
  routes: DayRoute[]
  warnings: string[]
}

export interface ChecklistItem {
  id: string
  category: string
  name: string
  checked: boolean
  autoGenerated: boolean
}

export const PREFERENCE_LABELS: Record<Preference, string> = {
  scenic: '看景',
  family: '亲子',
  camping: '露营',
  less_mountain: '少走山路',
}

export const VEHICLE_LABELS: Record<VehicleType, string> = {
  fuel: '燃油车',
  electric: '电动车',
  hybrid: '混动车',
}
