export type VehicleType = 'fuel' | 'electric' | 'hybrid'
export type Preference = 'scenic' | 'family' | 'camping' | 'less_mountain'
export type SpotType = 'scenic' | 'restaurant' | 'hotel' | 'service_area' | 'rest'
export type OptimizationType = 'less_drive' | 'early_hotel' | 'add_lunch'
export type PlanStyle = 'relaxed' | 'scenic' | 'efficient'
export type TimeSegment = 'morning' | 'lunch' | 'afternoon' | 'evening' | 'hotel'

export interface TripParams {
  departure: string
  days: number
  companions: number
  vehicleType: VehicleType
  dailyDriveHours: number
  preferences: Preference[]
}

export interface Spot {
  id: string
  name: string
  type: SpotType
  arrivalTime: string
  duration: number
  mileage: number
  description: string
  timeSegment: TimeSegment
}

export interface DayRoute {
  day: number
  date: string
  totalMileage: number
  drivingDuration: number
  serviceAreas: string[]
  fuelChargeSuggestion: string
  spots: Spot[]
}

export interface CostEstimate {
  fuelCost: number
  fuelCostRange: string
  parkingCost: number
  parkingCostRange: string
  hotelCost: number
  hotelCostRange: string
  totalCost: number
  totalCostRange: string
  chargeStops: number
  chargeCost: number
}

export interface DayCompareInfo {
  day: number
  drivingHours: number
  intensity: '轻松' | '适中' | '较累' | '很累'
}

export interface ItineraryData {
  id: string
  style: PlanStyle
  styleName: string
  styleDesc: string
  params: TripParams
  routes: DayRoute[]
  warnings: string[]
  alternativeSpots: string[]
  costEstimate: CostEstimate
  targetAudience: string
  hardestDay: number
  dayCompare: DayCompareInfo[]
}

export interface ChecklistItem {
  id: string
  category: string
  group: 'vehicle' | 'clothing' | 'energy' | 'family' | 'camping' | 'documents' | 'emergency' | 'other'
  name: string
  checked: boolean
  autoGenerated: boolean
  isDaily: boolean
}

export const PLAN_STYLES: Record<PlanStyle, { name: string; desc: string; icon: string }> = {
  relaxed: { name: '轻松版', desc: '每日驾驶不超过4小时，景点少而精，适合老人小孩', icon: '🌿' },
  scenic: { name: '风景版', desc: '精选沿途精华景点，停车拍照点多，不留遗憾', icon: '📸' },
  efficient: { name: '效率版', desc: '每日驾驶5-6小时，覆盖更多目的地，赶时间首选', icon: '⚡' },
}

export const PREFERENCE_LABELS: Record<Preference, string> = {
  scenic: '看景',
  family: '亲子',
  camping: '露营',
  less_mountain: '少走山路',
}

export const VEHICLE_LABELS: Record<VehicleType, string> = {
  fuel: '燃油车',
  electric: '电动车',
  hybrid: '混动车',
}

export const CHECKLIST_GROUPS: Record<string, { label: string; icon: string; order: number }> = {
  documents: { label: '证件资料', icon: '📄', order: 1 },
  vehicle: { label: '车辆装备', icon: '🚗', order: 2 },
  energy: { label: '补能用品', icon: '⚡', order: 3 },
  clothing: { label: '衣物保暖', icon: '👕', order: 4 },
  family: { label: '亲子用品', icon: '👶', order: 5 },
  camping: { label: '露营装备', icon: '⛺', order: 6 },
  emergency: { label: '应急药品', icon: '💊', order: 7 },
  other: { label: '其他物品', icon: '📦', order: 8 },
}

export const TIME_SEGMENT_LABELS: Record<TimeSegment, { label: string; color: string }> = {
  morning: { label: '上午', color: 'bg-amber-100 text-amber-700' },
  lunch: { label: '午餐', color: 'bg-sunset-100 text-sunset-700' },
  afternoon: { label: '下午', color: 'bg-forest-100 text-forest-700' },
  evening: { label: '傍晚', color: 'bg-sand-200 text-sand-700' },
  hotel: { label: '入住', color: 'bg-sand-300 text-sand-800' },
}
